title: "Kazuki Yano"
description: "Ph.D. Student in Information Science at Tohoku University"
url: "https://Kazuki-Ya.github.io"
baseurl: ""

author:
  name: "Kazuki Yano"
  email: "yano.kazuki@dc.tohoku.ac.jp"
  github: "Kazuki-Ya"
  twitter: "kyano__nlp"
  google_scholar: "KnttZUwAAAAJ"  # Google Scholar user ID を入れる（URLの ?user=XXXXX の部分）

markdown: kramdown
kramdown:
  input: GFM

permalink: /blog/:title/

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - vendor

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

plugins:
  - jekyll-feed
  - jekyll-sitemap
